[package]
name = "rta"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.41"
charming = { version = "0.6.0", features = ["ssr"] }
polars = { version = "0.49.1", features = ["lazy", "parquet", "csv"] }
